# Service definitions for the Byte-Watt integration

force_reconnect:
  name: Force Reconnect
  description: >-
    Force the ByteWatt integration to reconnect to the API when it appears to be stuck.
    Use this service if your ByteWatt integration has stopped updating and shows stale data.
    This will reset the client connection, authenticate again, and refresh all sensor data.

health_check:
  name: Health Check
  description: >-
    Run a comprehensive health check on the ByteWatt integration.
    This will check network connectivity, authentication, and API accessibility.
    Results will be displayed in a persistent notification.
  fields:
    entry_id:
      name: Integration ID
      description: The ID of the specific integration to check (optional, checks all if not provided)
      example: "abcdef1234"
      required: false
      selector:
        text:

toggle_diagnostics:
  name: Toggle Diagnostics
  description: >-
    Enable or disable detailed diagnostic logging for the ByteWatt integration.
    When enabled, detailed logs will be collected about API operations, errors, and recovery attempts.
  fields:
    enable:
      name: Enable
      description: Set to true to enable diagnostics, false to disable (toggles current state if not provided)
      required: false
      example: true
      selector:
        boolean:
    entry_id:
      name: Integration ID
      description: The ID of the specific integration to modify (optional, affects all if not provided)
      example: "abcdef1234"
      required: false
      selector:
        text:

set_discharge_time:
  name: Set Discharge End Time
  description: Set the end time for battery discharge (legacy service)
  fields:
    end_discharge:
      name: End Discharge Time
      description: The time when battery discharge should end (format HH:MM)
      example: "23:00"
      required: true
      selector:
        time: {}

set_discharge_start_time:
  name: Set Discharge Start Time
  description: Set the start time for battery discharge
  fields:
    start_discharge:
      name: Start Discharge Time
      description: The time when battery discharge should start (format HH:MM)
      example: "16:00"
      required: true
      selector:
        time: {}

set_charge_start_time:
  name: Set Charge Start Time
  description: Set the start time for battery charging
  fields:
    start_charge:
      name: Start Charge Time
      description: The time when battery charging should start (format HH:MM)
      example: "14:30"
      required: true
      selector:
        time: {}

set_charge_end_time:
  name: Set Charge End Time
  description: Set the end time for battery charging
  fields:
    end_charge:
      name: End Charge Time
      description: The time when battery charging should end (format HH:MM)
      example: "16:00"
      required: true
      selector:
        time: {}

set_minimum_soc:
  name: Set Minimum SOC
  description: Set the minimum battery state of charge percentage
  fields:
    minimum_soc:
      name: Minimum SOC
      description: The minimum battery state of charge to maintain (1-100%)
      example: 10
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"

set_charge_cap:
  name: Set Charge Cap
  description: Set the maximum battery charge cap percentage
  fields:
    charge_cap:
      name: Charge Cap
      description: The maximum battery charge cap to maintain (1-100%)
      example: 90
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"

update_battery_settings:
  name: Update Battery Settings
  description: Update multiple battery settings at once
  fields:
    start_discharge:
      name: Start Discharge Time
      description: The time when battery discharge should start (format HH:MM)
      example: "16:00"
      required: false
      selector:
        time: {}
    end_discharge:
      name: End Discharge Time
      description: The time when battery discharge should end (format HH:MM)
      example: "23:00"
      required: false
      selector:
        time: {}
    start_charge:
      name: Start Charge Time
      description: The time when battery charging should start (format HH:MM)
      example: "14:30"
      required: false
      selector:
        time: {}
    end_charge:
      name: End Charge Time
      description: The time when battery charging should end (format HH:MM)
      example: "16:00"
      required: false
      selector:
        time: {}
    minimum_soc:
      name: Minimum SOC
      description: The minimum battery state of charge to maintain (1-100%)
      example: 10
      required: false
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
    charge_cap:
      name: Charge Cap
      description: The maximum battery charge cap to maintain (1-100%)
      example: 90
      required: false
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
